/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.inventory;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nova
 */
public class CheckInProducts extends javax.swing.JInternalFrame {

    /**
     * Creates new form CheckInProducts
     */
    public CheckInProducts() {
        initComponents();
         this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
          model = (DefaultTableModel) CheckInProductsTable.getModel();
        updateTable(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CheckInProductsScrollPane = new javax.swing.JScrollPane();
        CheckInProductsTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        DateLabel = new javax.swing.JLabel();
        PILabel = new javax.swing.JLabel();
        CheckInButton = new javax.swing.JButton();
        PITF = new javax.swing.JTextField();
        ClearButton = new javax.swing.JButton();
        QTYTOADDEDTF = new javax.swing.JTextField();
        QtyToaddLabel = new javax.swing.JLabel();
        WNTF = new javax.swing.JTextField();
        WorkerNamelabel = new javax.swing.JLabel();
        DateTF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(51, 51, 51));

        CheckInProductsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Quantity", "Price", "EXP", "Company name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        CheckInProductsTable.getTableHeader().setReorderingAllowed(false);
        CheckInProductsScrollPane.setViewportView(CheckInProductsTable);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        DateLabel.setFont(new java.awt.Font("Sama Devanagari", 0, 13)); // NOI18N
        DateLabel.setForeground(new java.awt.Color(255, 255, 255));
        DateLabel.setText("Date (yyyy-mm-dd):");

        PILabel.setFont(new java.awt.Font("Sama Devanagari", 0, 13)); // NOI18N
        PILabel.setForeground(new java.awt.Color(255, 255, 255));
        PILabel.setText("Product ID :");

        CheckInButton.setText("Check In");
        CheckInButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CheckInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckInButtonMouseClicked(evt);
            }
        });

        PITF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PITFActionPerformed(evt);
            }
        });

        ClearButton.setText("Clear");
        ClearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearButtonMouseClicked(evt);
            }
        });
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        QTYTOADDEDTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QTYTOADDEDTFActionPerformed(evt);
            }
        });

        QtyToaddLabel.setFont(new java.awt.Font("Sama Devanagari", 0, 13)); // NOI18N
        QtyToaddLabel.setForeground(new java.awt.Color(255, 255, 255));
        QtyToaddLabel.setText("Quantity to Add");

        WNTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WNTFActionPerformed(evt);
            }
        });

        WorkerNamelabel.setFont(new java.awt.Font("Sama Devanagari", 0, 13)); // NOI18N
        WorkerNamelabel.setForeground(new java.awt.Color(255, 255, 255));
        WorkerNamelabel.setText("Worker Name");

        DateTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateTFActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QtyToaddLabel)
                            .addComponent(PILabel)
                            .addComponent(WorkerNamelabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WNTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PITF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QTYTOADDEDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CheckInButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ClearButton)))
                .addContainerGap(43, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PILabel)
                    .addComponent(PITF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QtyToaddLabel)
                    .addComponent(QTYTOADDEDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WorkerNamelabel)
                    .addComponent(WNTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateLabel)
                    .addComponent(DateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckInButton)
                    .addComponent(ClearButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CheckInProductsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CheckInProductsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateTFActionPerformed
       
    }//GEN-LAST:event_DateTFActionPerformed

    private void CheckInButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckInButtonMouseClicked
     int productId, quantityToAdd;
        String workerName, date;

        try {
            productId = Integer.parseInt(PITF.getText());
            quantityToAdd = Integer.parseInt(QTYTOADDEDTF.getText());
            workerName = WNTF.getText();
            date = DateTF.getText();

            updateDatabase(productId, quantityToAdd, workerName, date);
             String message = "Product ID: " + productId + "\n" +
                            "Quantity Added: " + quantityToAdd + "\n" +
                            "Worker Name: " + workerName + "\n" +
                            "Date: " + date;

         // TwilioHandler.sendMessage(message);

            PITF.setText("");
            QTYTOADDEDTF.setText("");
            WNTF.setText("");
            DateTF.setText("");

            updateTable(model);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid input. Please enter numbers.");
        }
 
    }//GEN-LAST:event_CheckInButtonMouseClicked

     private void updateTable(DefaultTableModel model) {
        model.setRowCount(0); // Clear the table
    try {
        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory", "root", "root");
        PreparedStatement st = connection.prepareStatement(
                "SELECT * FROM Products"
        );
        var rs = st.executeQuery();
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("item_id"),
                rs.getString("item_name"),
                rs.getInt("quantity"),
                rs.getInt("price"),
                rs.getString("exp_date"),
                rs.getString("Company_Name")
            });
        }
        connection.close();
    } catch (SQLException ex) {
        ex.printStackTrace();
        // Handle database error (e.g., show error message)
    }
    }
     
     
 
    private void updateDatabase(int productId, int quantityToAdd, String workerName, String date) {
        String jdbcURL = "jdbc:mysql://localhost:3306/inventory";
        String username = "root";
        String password = "root";
        Connection connection = null;

        try {
            connection = DriverManager.getConnection(jdbcURL, username, password);
            connection.setAutoCommit(false);

            String checkInsSql = "INSERT INTO CheckIns (item_id, worker_name, amount_added, checkin_date) VALUES (?, ?, ?, ?)";
            try (PreparedStatement checkInsStatement = connection.prepareStatement(checkInsSql)) {
                checkInsStatement.setInt(1, productId);
                checkInsStatement.setString(2, workerName);
                checkInsStatement.setInt(3, quantityToAdd);
                checkInsStatement.setString(4, date);
                checkInsStatement.executeUpdate();
            }

            String productsSql = "UPDATE Products SET quantity = quantity + ? WHERE item_id = ?";
            try (PreparedStatement productsStatement = connection.prepareStatement(productsSql)) {
                productsStatement.setInt(1, quantityToAdd);
                productsStatement.setInt(2, productId);
                productsStatement.executeUpdate();
            }

            connection.commit();
            connection.setAutoCommit(true);

            JOptionPane.showMessageDialog(this, "Check-in successful!");
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            try {
                if (connection != null) {
                    connection.rollback();
                    connection.setAutoCommit(true);
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        } finally {
            try {
                if (connection != null && !connection.isClosed()) {
                    connection.close();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }
    
    
 
 
    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        int[] selectedRows = CheckInProductsTable.getSelectedRows();

        for (int i = selectedRows.length - 1; i >= 0; i--) {
            model.removeRow(selectedRows[i]);
        }
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void ClearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearButtonMouseClicked

    private void QTYTOADDEDTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QTYTOADDEDTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QTYTOADDEDTFActionPerformed

    private void WNTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WNTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WNTFActionPerformed

    private void PITFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PITFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PITFActionPerformed

private DefaultTableModel model;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckInButton;
    private javax.swing.JScrollPane CheckInProductsScrollPane;
    private javax.swing.JTable CheckInProductsTable;
    private javax.swing.JButton ClearButton;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JTextField DateTF;
    private javax.swing.JLabel PILabel;
    private javax.swing.JTextField PITF;
    private javax.swing.JTextField QTYTOADDEDTF;
    private javax.swing.JLabel QtyToaddLabel;
    private javax.swing.JTextField WNTF;
    private javax.swing.JLabel WorkerNamelabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
