/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventory;

import java.awt.Color;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author fahim
 */
public class UserHome extends javax.swing.JFrame {

    private static String username;
    private static String admin;
    Color DefaultColor,ClickedColor;

    public UserHome(String username,String admin) {
        this.username = username;
        this.admin=admin;
        initComponents();
       DefaultColor  = new Color(51,51,51);
       ClickedColor = new Color(106,175,243);
       
      Addprodpanel.setBackground(DefaultColor);
      searchprodpanel.setBackground(DefaultColor);
      viewprodpanel.setBackground(DefaultColor);
      activitypanel.setBackground(DefaultColor);
      statpanel.setBackground(DefaultColor);
       
       
       
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        FullPanel = new javax.swing.JPanel();
        UpperPanel = new javax.swing.JPanel();
        AdminButton = new javax.swing.JButton();
        Menu = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        menuName = new javax.swing.JLabel();
        Chat = new javax.swing.JButton();
        LowerPanel = new javax.swing.JPanel();
        Logout = new javax.swing.JButton();
        searchprodpanel = new javax.swing.JPanel();
        SearchProducts = new javax.swing.JLabel();
        Addprodpanel = new javax.swing.JPanel();
        AddProducs1 = new javax.swing.JLabel();
        viewprodpanel = new javax.swing.JPanel();
        ViewProducts = new javax.swing.JLabel();
        activitypanel = new javax.swing.JPanel();
        ActivityHistory = new javax.swing.JLabel();
        statpanel = new javax.swing.JPanel();
        Statistics = new javax.swing.JLabel();
        DesktopPanel = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        Title1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Title2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TotalProd1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        TotalQtyOrdered = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        TotalIN = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        TopSellingItem = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        TotalOUT = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel13 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        LowProd1 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        LowProd = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FullPanel.setBackground(new java.awt.Color(51, 51, 51));
        FullPanel.setPreferredSize(new java.awt.Dimension(1180, 640));
        FullPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UpperPanel.setBackground(new java.awt.Color(210, 210, 210));
        UpperPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminButton.setBackground(new java.awt.Color(106, 175, 243));
        AdminButton.setText("My Profile");
        AdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonActionPerformed(evt);
            }
        });
        UpperPanel.add(AdminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(956, 21, -1, -1));

        Menu.setFont(new java.awt.Font("PT Sans", 1, 18)); // NOI18N
        Menu.setText("Add Product");
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuMousePressed(evt);
            }
        });
        UpperPanel.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, 17));

        jPanel7.setBackground(new java.awt.Color(60, 60, 60));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuName.setFont(new java.awt.Font("PT Sans", 1, 18)); // NOI18N
        menuName.setForeground(new java.awt.Color(238, 238, 238));
        menuName.setText("Inevntory Nexus");
        menuName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuNameMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuNameMousePressed(evt);
            }
        });
        jPanel7.add(menuName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        UpperPanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 63));

        Chat.setText("Chat");
        Chat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChatActionPerformed(evt);
            }
        });
        UpperPanel.add(Chat, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, -1));

        FullPanel.add(UpperPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        LowerPanel.setBackground(new java.awt.Color(51, 51, 51));
        LowerPanel.setForeground(new java.awt.Color(255, 204, 204));
        LowerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logout.setText("Logout");
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        LowerPanel.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, -1));

        searchprodpanel.setBackground(new java.awt.Color(51, 51, 51));
        searchprodpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchprodpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchprodpanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchprodpanelMousePressed(evt);
            }
        });

        SearchProducts.setForeground(new java.awt.Color(255, 255, 255));
        SearchProducts.setText("Search Product");
        SearchProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SearchProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchProductsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SearchProductsMousePressed(evt);
            }
        });

        javax.swing.GroupLayout searchprodpanelLayout = new javax.swing.GroupLayout(searchprodpanel);
        searchprodpanel.setLayout(searchprodpanelLayout);
        searchprodpanelLayout.setHorizontalGroup(
            searchprodpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchprodpanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(SearchProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        searchprodpanelLayout.setVerticalGroup(
            searchprodpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchprodpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchProducts, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        LowerPanel.add(searchprodpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 180, 40));

        Addprodpanel.setBackground(new java.awt.Color(51, 51, 51));
        Addprodpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Addprodpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddprodpanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AddprodpanelMousePressed(evt);
            }
        });

        AddProducs1.setForeground(new java.awt.Color(255, 255, 255));
        AddProducs1.setText("Add Product");
        AddProducs1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddProducs1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddProducs1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AddProducs1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout AddprodpanelLayout = new javax.swing.GroupLayout(Addprodpanel);
        Addprodpanel.setLayout(AddprodpanelLayout);
        AddprodpanelLayout.setHorizontalGroup(
            AddprodpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddprodpanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(AddProducs1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        AddprodpanelLayout.setVerticalGroup(
            AddprodpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddprodpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddProducs1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        LowerPanel.add(Addprodpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 180, 40));

        viewprodpanel.setBackground(new java.awt.Color(51, 51, 51));
        viewprodpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewprodpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewprodpanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viewprodpanelMousePressed(evt);
            }
        });

        ViewProducts.setForeground(new java.awt.Color(255, 255, 255));
        ViewProducts.setText("View Products");
        ViewProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewProductsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ViewProductsMousePressed(evt);
            }
        });

        javax.swing.GroupLayout viewprodpanelLayout = new javax.swing.GroupLayout(viewprodpanel);
        viewprodpanel.setLayout(viewprodpanelLayout);
        viewprodpanelLayout.setHorizontalGroup(
            viewprodpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewprodpanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(ViewProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        viewprodpanelLayout.setVerticalGroup(
            viewprodpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewprodpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ViewProducts, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        LowerPanel.add(viewprodpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        activitypanel.setBackground(new java.awt.Color(51, 51, 51));
        activitypanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        activitypanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                activitypanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                activitypanelMousePressed(evt);
            }
        });

        ActivityHistory.setForeground(new java.awt.Color(255, 255, 255));
        ActivityHistory.setText("Activity History");
        ActivityHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ActivityHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActivityHistoryMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ActivityHistoryMousePressed(evt);
            }
        });

        javax.swing.GroupLayout activitypanelLayout = new javax.swing.GroupLayout(activitypanel);
        activitypanel.setLayout(activitypanelLayout);
        activitypanelLayout.setHorizontalGroup(
            activitypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activitypanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(ActivityHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        activitypanelLayout.setVerticalGroup(
            activitypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, activitypanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ActivityHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        LowerPanel.add(activitypanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        statpanel.setBackground(new java.awt.Color(51, 51, 51));
        statpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statpanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                statpanelMousePressed(evt);
            }
        });

        Statistics.setForeground(new java.awt.Color(255, 255, 255));
        Statistics.setText("Statistics");
        Statistics.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Statistics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StatisticsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StatisticsMousePressed(evt);
            }
        });

        javax.swing.GroupLayout statpanelLayout = new javax.swing.GroupLayout(statpanel);
        statpanel.setLayout(statpanelLayout);
        statpanelLayout.setHorizontalGroup(
            statpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statpanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(Statistics)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        statpanelLayout.setVerticalGroup(
            statpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Statistics, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        LowerPanel.add(statpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        FullPanel.add(LowerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 59, 180, 580));

        DesktopPanel.setPreferredSize(new java.awt.Dimension(870, 551));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 66, 465, 10));

        Title1.setBackground(new java.awt.Color(255, 255, 255));
        Title1.setFont(new java.awt.Font("PT Sans", 1, 36)); // NOI18N
        Title1.setForeground(new java.awt.Color(255, 255, 255));
        Title1.setText("Inventory Nexus!");
        Title1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 262, -1, -1));

        jLabel7.setFont(new java.awt.Font("Sama Devanagari", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(238, 238, 238));
        jLabel7.setText("Activity");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 26, 75, -1));

        Title2.setBackground(new java.awt.Color(255, 255, 255));
        Title2.setFont(new java.awt.Font("Symbol", 0, 24)); // NOI18N
        Title2.setForeground(new java.awt.Color(255, 255, 255));
        Title2.setText("Welcome to");
        Title2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(Title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 231, -1, -1));

        jLabel8.setFont(new java.awt.Font("Sama Devanagari", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(238, 238, 238));
        jLabel8.setText("Inevntory Summary");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 316, 169, -1));

        jPanel6.setBackground(new java.awt.Color(106, 175, 243));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("PT Sans", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total Products");

        TotalProd1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        TotalProd1.setForeground(new java.awt.Color(255, 255, 255));
        TotalProd1.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(TotalProd1)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TotalProd1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 94, -1, -1));

        jPanel10.setBackground(new java.awt.Color(106, 106, 106));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("PT Sans", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total Price : ");

        TotalQtyOrdered.setText("0");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(TotalQtyOrdered)
                .addGap(56, 56, 56))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TotalQtyOrdered))
                .addContainerGap())
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 441, 224, -1));

        jPanel8.setBackground(new java.awt.Color(106, 175, 243));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("PT Sans", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Check IN");

        TotalIN.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        TotalIN.setForeground(new java.awt.Color(255, 255, 255));
        TotalIN.setText("0");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(TotalIN)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TotalIN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 94, -1, -1));

        jPanel11.setBackground(new java.awt.Color(106, 106, 106));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("PT Sans", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Top Ordered Items :");

        TopSellingItem.setText("0");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TopSellingItem)
                .addGap(58, 58, 58))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TopSellingItem))
                .addContainerGap())
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 384, -1, -1));

        jPanel9.setBackground(new java.awt.Color(106, 175, 243));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("PT Sans", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total Check OUT");

        TotalOUT.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        TotalOUT.setForeground(new java.awt.Color(255, 255, 255));
        TotalOUT.setText("0");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(TotalOUT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(15, 15, 15))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 94, 140, 100));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 356, 465, 10));

        jPanel13.setBackground(new java.awt.Color(106, 175, 243));
        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setFont(new java.awt.Font("PT Sans", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Low Products");

        LowProd1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        LowProd1.setForeground(new java.awt.Color(255, 255, 255));
        LowProd1.setText("0");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel13))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(LowProd1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LowProd1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 200, -1));

        DesktopPanel.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopPanelLayout = new javax.swing.GroupLayout(DesktopPanel);
        DesktopPanel.setLayout(DesktopPanelLayout);
        DesktopPanelLayout.setHorizontalGroup(
            DesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DesktopPanelLayout.setVerticalGroup(
            DesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        FullPanel.add(DesktopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 900, 580));

        getContentPane().add(FullPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        jPanel12.setBackground(new java.awt.Color(106, 175, 243));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setFont(new java.awt.Font("PT Sans", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Low Products");

        LowProd.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        LowProd.setForeground(new java.awt.Color(255, 255, 255));
        LowProd.setText("0");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel12))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(LowProd)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LowProd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StatisticsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatisticsMousePressed
        Menu.setText("Statistics");
    }//GEN-LAST:event_StatisticsMousePressed

    private void StatisticsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StatisticsMouseClicked
        Stat s = new Stat();
        DesktopPanel.removeAll();
        DesktopPanel.add(s).setVisible(true);
    }//GEN-LAST:event_StatisticsMouseClicked

    private void ActivityHistoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActivityHistoryMousePressed
        Menu.setText("Activity History");
    }//GEN-LAST:event_ActivityHistoryMousePressed

    private void ActivityHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActivityHistoryMouseClicked
        try {
            // TODO add your handling code here:
            ActivityHistory a=new ActivityHistory();
            DesktopPanel.removeAll();
            DesktopPanel.add(a).setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(UserHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ActivityHistoryMouseClicked

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutActionPerformed

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // Create an instance of the WorkerLogin window
        UserLogin userlogin = new UserLogin();

        // Make the WorkerLogin window visible
        userlogin.setVisible(true);

        // Close the current WorkerHome window
        this.dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    private void SearchProductsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchProductsMousePressed
        Menu.setText("Search Products");
    }//GEN-LAST:event_SearchProductsMousePressed

    private void SearchProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchProductsMouseClicked
        // TODO add your handling code here:
        SearchProduct search = new SearchProduct();
        DesktopPanel.removeAll();
        DesktopPanel.add(search).setVisible(true);
    }//GEN-LAST:event_SearchProductsMouseClicked

    private void menuNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuNameMousePressed
        Menu.setText("Home");
    }//GEN-LAST:event_menuNameMousePressed

    private void menuNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuNameMouseClicked
        AdminHomePage ahp = new AdminHomePage();
        DesktopPanel.removeAll();
        DesktopPanel.add(ahp).setVisible(true);
    }//GEN-LAST:event_menuNameMouseClicked

    private void MenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuMousePressed

    private void MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuMouseClicked

    private void AdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonActionPerformed
        Profile prof = new Profile(username,admin);
        DesktopPanel.removeAll();
        DesktopPanel.add(prof).setVisible(true);
    }//GEN-LAST:event_AdminButtonActionPerformed

    private void AddProducs1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddProducs1MouseClicked
         AddProduct ap = new AddProduct();
        DesktopPanel.removeAll();
        DesktopPanel.add(ap).setVisible(true);
    }//GEN-LAST:event_AddProducs1MouseClicked

    private void AddProducs1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddProducs1MousePressed
         Menu.setText("Add Products");
    }//GEN-LAST:event_AddProducs1MousePressed

    private void ViewProductsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewProductsMousePressed
        Menu.setText("View Products");
    }//GEN-LAST:event_ViewProductsMousePressed

    private void ViewProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewProductsMouseClicked
        ViewProductsAdmin vpa = new ViewProductsAdmin();
        DesktopPanel.removeAll();
        DesktopPanel.add(vpa).setVisible(true);
    }//GEN-LAST:event_ViewProductsMouseClicked

    private void AddprodpanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddprodpanelMousePressed
             Menu.setText("Add Products");
             Addprodpanel.setBackground(ClickedColor);
 
      searchprodpanel.setBackground(DefaultColor);
      viewprodpanel.setBackground(DefaultColor);
      activitypanel.setBackground(DefaultColor);
      statpanel.setBackground(DefaultColor);
       
    }//GEN-LAST:event_AddprodpanelMousePressed

    private void searchprodpanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchprodpanelMousePressed
      
        Menu.setText("Search Products");  Addprodpanel.setBackground(DefaultColor);
      searchprodpanel.setBackground(ClickedColor);
      viewprodpanel.setBackground(DefaultColor);
      activitypanel.setBackground(DefaultColor);
      statpanel.setBackground(DefaultColor);
       
    }//GEN-LAST:event_searchprodpanelMousePressed

    private void viewprodpanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewprodpanelMousePressed
      Menu.setText("View Products"); Addprodpanel.setBackground(DefaultColor);
      searchprodpanel.setBackground(DefaultColor);
      viewprodpanel.setBackground(ClickedColor);
      activitypanel.setBackground(DefaultColor);
      statpanel.setBackground(DefaultColor);
       
    }//GEN-LAST:event_viewprodpanelMousePressed

    private void activitypanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activitypanelMousePressed
     Menu.setText("Activity History");Addprodpanel.setBackground(DefaultColor);
      searchprodpanel.setBackground(DefaultColor);
      viewprodpanel.setBackground(DefaultColor);
      activitypanel.setBackground(ClickedColor);
      statpanel.setBackground(DefaultColor);
       
    }//GEN-LAST:event_activitypanelMousePressed

    private void statpanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statpanelMousePressed
         Addprodpanel.setBackground(DefaultColor);
      searchprodpanel.setBackground(DefaultColor);
      viewprodpanel.setBackground(DefaultColor);
      activitypanel.setBackground(DefaultColor);
      statpanel.setBackground(ClickedColor);
       
    }//GEN-LAST:event_statpanelMousePressed

    private void AddprodpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddprodpanelMouseClicked
 AddProduct ap = new AddProduct();
        DesktopPanel.removeAll();
        DesktopPanel.add(ap).setVisible(true);
    }//GEN-LAST:event_AddprodpanelMouseClicked

    private void searchprodpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchprodpanelMouseClicked
  // TODO add your handling code here:
        SearchProduct search = new SearchProduct();
        DesktopPanel.removeAll();
        DesktopPanel.add(search).setVisible(true);
    }//GEN-LAST:event_searchprodpanelMouseClicked

    private void viewprodpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewprodpanelMouseClicked
    ViewProductsAdmin vpa = new ViewProductsAdmin();
        DesktopPanel.removeAll();
        DesktopPanel.add(vpa).setVisible(true);
    }//GEN-LAST:event_viewprodpanelMouseClicked

    private void activitypanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activitypanelMouseClicked
          try {
            // TODO add your handling code here:
            ActivityHistory a=new ActivityHistory();
            DesktopPanel.removeAll();
            DesktopPanel.add(a).setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(UserHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_activitypanelMouseClicked

    private void statpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statpanelMouseClicked
            Menu.setText("Statistics"); Stat s = new Stat();
        DesktopPanel.removeAll();
        DesktopPanel.add(s).setVisible(true);
    }//GEN-LAST:event_statpanelMouseClicked

    private void ChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChatActionPerformed
       chatWindowAdmin wa=new chatWindowAdmin(username);
        DesktopPanel.removeAll();
        DesktopPanel.add(wa).setVisible(true);
    }//GEN-LAST:event_ChatActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserHome(username,admin).setVisible(true);
            }
        });
    }


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActivityHistory;
    private javax.swing.JLabel AddProducs1;
    private javax.swing.JPanel Addprodpanel;
    private javax.swing.JButton AdminButton;
    private javax.swing.JButton Chat;
    private javax.swing.JDesktopPane DesktopPanel;
    private javax.swing.JPanel FullPanel;
    private javax.swing.JButton Logout;
    private javax.swing.JLabel LowProd;
    private javax.swing.JLabel LowProd1;
    private javax.swing.JPanel LowerPanel;
    private javax.swing.JLabel Menu;
    private javax.swing.JLabel SearchProducts;
    private javax.swing.JLabel Statistics;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel TopSellingItem;
    private javax.swing.JLabel TotalIN;
    private javax.swing.JLabel TotalOUT;
    private javax.swing.JLabel TotalProd1;
    private javax.swing.JLabel TotalQtyOrdered;
    private javax.swing.JPanel UpperPanel;
    private javax.swing.JLabel ViewProducts;
    private javax.swing.JPanel activitypanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel menuName;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private javax.swing.JPanel searchprodpanel;
    private javax.swing.JPanel statpanel;
    private javax.swing.JPanel viewprodpanel;
    // End of variables declaration//GEN-END:variables
}
