/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventory;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
    import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

/**
 *
 * @author fahim
 */
public class WorkerLogin extends javax.swing.JFrame {

    /**
     * Creates new form WorkerLogin
     */
    public WorkerLogin() {
        initComponents();
         
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        BG_Main = new javax.swing.JPanel();
        BG_1 = new javax.swing.JPanel();
        Title1 = new javax.swing.JLabel();
        Title2 = new javax.swing.JLabel();
        UserName = new javax.swing.JLabel();
        WorkerName = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        workerpassword = new javax.swing.JPasswordField();
        Title3 = new javax.swing.JLabel();
        loginbutton = new javax.swing.JButton();
        Title4 = new javax.swing.JLabel();
        Title5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Worker Login ");
        setBackground(new java.awt.Color(51, 51, 51));

        BG_Main.setBackground(new java.awt.Color(51, 51, 51));
        BG_Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BG_1.setBackground(new java.awt.Color(70, 70, 70));

        Title1.setFont(new java.awt.Font("PT Sans", 1, 24)); // NOI18N
        Title1.setForeground(new java.awt.Color(230, 230, 230));
        Title1.setLabelFor(BG_1);
        Title1.setText("Welcome Back!");
        Title1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        Title2.setForeground(new java.awt.Color(210, 210, 210));
        Title2.setText("Please sign in to access your account");

        UserName.setFont(new java.awt.Font("PT Sans", 0, 14)); // NOI18N
        UserName.setForeground(new java.awt.Color(230, 230, 230));
        UserName.setText("Username");

        WorkerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkerNameActionPerformed(evt);
            }
        });

        password.setFont(new java.awt.Font("PT Sans", 0, 14)); // NOI18N
        password.setForeground(new java.awt.Color(230, 230, 230));
        password.setText("Password");

        Title3.setForeground(new java.awt.Color(210, 210, 210));
        Title3.setText("Don't have an account?");

        loginbutton.setBackground(new java.awt.Color(210, 210, 210));
        loginbutton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        loginbutton.setText("Login");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });

        Title4.setForeground(new java.awt.Color(255, 255, 255));
        Title4.setText("Sign_up");
        Title4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Title4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Title4MouseClicked(evt);
            }
        });

        Title5.setForeground(new java.awt.Color(255, 255, 255));
        Title5.setText("« Back");
        Title5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Title5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Title5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BG_1Layout = new javax.swing.GroupLayout(BG_1);
        BG_1.setLayout(BG_1Layout);
        BG_1Layout.setHorizontalGroup(
            BG_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_1Layout.createSequentialGroup()
                .addGroup(BG_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BG_1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(Title3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Title4))
                    .addGroup(BG_1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(BG_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Title5)
                            .addGroup(BG_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(password)
                                .addComponent(UserName)
                                .addComponent(Title2)
                                .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(WorkerName)
                                .addComponent(workerpassword)
                                .addComponent(loginbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        BG_1Layout.setVerticalGroup(
            BG_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Title2)
                .addGap(18, 18, 18)
                .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WorkerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workerpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(loginbutton)
                .addGap(18, 18, 18)
                .addComponent(Title5)
                .addGap(13, 13, 13)
                .addGroup(BG_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title3)
                    .addComponent(Title4))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        BG_Main.add(BG_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG_Main, javax.swing.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG_Main, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WorkerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkerNameActionPerformed

    }//GEN-LAST:event_WorkerNameActionPerformed

    private void Title4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Title4MouseClicked
        WorkerSignUp signUpWindow = new WorkerSignUp();
                signUpWindow.setVisible(true);
                dispose(); // Close the current login window
    }//GEN-LAST:event_Title4MouseClicked

    private void Title5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Title5MouseClicked
          UserTypeSelection userTypeSelection = new UserTypeSelection();
            userTypeSelection.setVisible(true);
            dispose(); // Close the current window
    }//GEN-LAST:event_Title5MouseClicked

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        // TODO add your handling code here:
         String workername = WorkerName.getText();
            String enteredPassword = new String(workerpassword.getPassword());

            try (Connection connection = DatabaseConnection.getConnection()) {
                String query = "SELECT * FROM worker WHERE name = ? AND pw = ?";
                try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
                    preparedStatement.setString(1, workername);
                    preparedStatement.setString(2, enteredPassword);
                    ResultSet resultSet = preparedStatement.executeQuery();

                    if (resultSet.next()) {
                        String status = resultSet.getString("status");
                        if (status.equals("APPROVED")) {
                            // Credentials are correct and worker is approved, open WorkerHome window
                            WorkerHome workerHome = new WorkerHome(workername,"worker");
                            workerHome.setVisible(true);
                            dispose(); // Close the current login window

                            // Show congratulatory message
                            JOptionPane.showMessageDialog(null, "Congratulations! You have successfully logged in.", "Login Successful", JOptionPane.INFORMATION_MESSAGE);
                        } else if (status.equals("PENDING")) {
                            // Worker's status is pending, display a message
                            JOptionPane.showMessageDialog(null, "Your account status is pending approval by the admin. Please wait for approval.", "Status Pending", JOptionPane.WARNING_MESSAGE);
                        }
                    } else {
                        // Credentials are incorrect, display error message
                        JOptionPane.showMessageDialog(null, "Incorrect workername or password. Please try again.", "Login Failed", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (SQLException ex) {
                // Handle database connection errors
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Database connection error.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
//GEN-LAST:event_loginbuttonActionPerformed



   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkerLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG_1;
    private javax.swing.JPanel BG_Main;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title3;
    private javax.swing.JLabel Title4;
    private javax.swing.JLabel Title5;
    private javax.swing.JLabel UserName;
    private javax.swing.JTextField WorkerName;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JButton loginbutton;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField workerpassword;
    // End of variables declaration//GEN-END:variables
}
