/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventory;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author nova
 */
public class WorkerSignUp extends javax.swing.JFrame {

    /**
     * Creates new form WorkerSignUp
     */
    public WorkerSignUp() {
        initComponents();
         initializeListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG_Main = new javax.swing.JPanel();
        BG_1 = new javax.swing.JPanel();
        Title1 = new javax.swing.JLabel();
        Title2 = new javax.swing.JLabel();
        UserName = new javax.swing.JLabel();
        WorkerName = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        workerpassword = new javax.swing.JPasswordField();
        signupbutton = new javax.swing.JButton();
        Title5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up : Worker");
        setBackground(new java.awt.Color(51, 51, 51));

        BG_Main.setBackground(new java.awt.Color(51, 51, 51));
        BG_Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BG_1.setBackground(new java.awt.Color(70, 70, 70));

        Title1.setFont(new java.awt.Font("PT Sans", 1, 24)); // NOI18N
        Title1.setForeground(new java.awt.Color(230, 230, 230));
        Title1.setText("Registration");
        Title1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        Title2.setForeground(new java.awt.Color(210, 210, 210));
        Title2.setText("Please sign up to create your account");

        UserName.setFont(new java.awt.Font("PT Sans", 0, 14)); // NOI18N
        UserName.setForeground(new java.awt.Color(230, 230, 230));
        UserName.setText("Username");

        WorkerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkerNameActionPerformed(evt);
            }
        });

        password.setFont(new java.awt.Font("PT Sans", 0, 14)); // NOI18N
        password.setForeground(new java.awt.Color(230, 230, 230));
        password.setText("Password");

        signupbutton.setBackground(new java.awt.Color(210, 210, 210));
        signupbutton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        signupbutton.setText("Sign up");

        Title5.setForeground(new java.awt.Color(255, 255, 255));
        Title5.setText("« Back");
        Title5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Title5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Title5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BG_1Layout = new javax.swing.GroupLayout(BG_1);
        BG_1.setLayout(BG_1Layout);
        BG_1Layout.setHorizontalGroup(
            BG_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(BG_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Title5)
                    .addGroup(BG_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(password)
                        .addComponent(UserName)
                        .addComponent(Title2)
                        .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(WorkerName)
                        .addComponent(workerpassword)
                        .addComponent(signupbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        BG_1Layout.setVerticalGroup(
            BG_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Title2)
                .addGap(18, 18, 18)
                .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WorkerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workerpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(signupbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Title5)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        BG_Main.add(BG_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BG_Main, javax.swing.GroupLayout.PREFERRED_SIZE, 993, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG_Main, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WorkerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkerNameActionPerformed

    }//GEN-LAST:event_WorkerNameActionPerformed

    private void Title5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Title5MouseClicked
        WorkerLogin workerLogin = new WorkerLogin();
    workerLogin.setVisible(true);
    dispose(); // Close the current window
    }//GEN-LAST:event_Title5MouseClicked


    private void signupbuttonActionPerformed(java.awt.event.ActionEvent evt) {
    String username = WorkerName.getText();
    String enteredPassword = new String(workerpassword.getPassword());

    // Validate input (you might want to add more validation logic)
    if (username.isEmpty() || enteredPassword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try (Connection connection = DatabaseConnection.getConnection()) {
        String query = "INSERT INTO worker (name, pw, status) VALUES (?, ?, 'PENDING')";
        try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
            preparedStatement.setString(1, username);
            // Store the password securely (consider hashing and salting)
            preparedStatement.setString(2, hashAndSaltPassword(enteredPassword));
            int rowsAffected = preparedStatement.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Registration successful. Status: PENDING", "Success", JOptionPane.INFORMATION_MESSAGE);
                dispose(); // Close the current registration window
            } else {
                JOptionPane.showMessageDialog(this, "Failed to create account. Please try again later.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    } catch (SQLException ex) {
        // Handle database connection errors
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Database connection error.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
 
private String hashAndSaltPassword(String password) {
    // Implement your password hashing and salting logic here
    // For example, you can use libraries like BCrypt to hash and salt the password
    // Return the hashed and salted password
    return password;
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkerSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkerSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkerSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkerSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkerSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG_1;
    private javax.swing.JPanel BG_Main;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title5;
    private javax.swing.JLabel UserName;
    private javax.swing.JTextField WorkerName;
    private javax.swing.JLabel password;
    private javax.swing.JButton signupbutton;
    private javax.swing.JPasswordField workerpassword;
    // End of variables declaration//GEN-END:variables

    private void initializeListeners() {
         signupbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbuttonActionPerformed(evt);
            }
        });
}
}
